use crate::shared::state::AppState;
use axum::Router;
use axum::routing::{delete, get, post, put};

pub fn public_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/identity/register",
            post(crate::handler::identity::registration::register),
        )
        .route(
            "/api/identity/login",
            post(crate::handler::identity::login::login),
        )
        .route(
            "/auth/refresh",
            post(crate::handler::identity::login::refresh),
        )
        .route(
            "/account/login",
            get(crate::handler::account::login::login_get)
                .post(crate::handler::account::login::login_post),
        )
        .route(
            "/account/social/{provider}/login",
            get(crate::handler::account::login::account_social_login),
        )
        .route(
            "/sso/login",
            get(crate::handler::sso::login::login_get).post(crate::handler::sso::login::login_post),
        )
        .route(
            "/sso/register",
            get(crate::handler::sso::register::register_get)
                .post(crate::handler::sso::register::register_post),
        )
        .route(
            "/sso/forgot-password",
            get(crate::handler::sso::forgot::forgot_get)
                .post(crate::handler::sso::forgot::forgot_post),
        )
        .route(
            "/sso/reset-password",
            get(crate::handler::sso::reset_password::reset_password_get)
                .post(crate::handler::sso::reset_password::reset_password_post),
        )
        .route(
            "/sso/verify-email",
            get(crate::handler::sso::verification::verify_email_get),
        )
        .route(
            "/sso/verify-phone",
            get(crate::handler::sso::verification::verify_phone_get)
                .post(crate::handler::sso::verification::verify_phone_post),
        )
        .route("/sso/error", get(crate::handler::sso::error::error_get))
}

pub fn account_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/account/profile",
            get(crate::handler::account::profile::profile_get)
                .post(crate::handler::account::profile::profile_post),
        )
        .route(
            "/account/profile/send-verify-email",
            post(crate::handler::account::profile::send_verify_email_post),
        )
        .route(
            "/account/profile/send-verify-phone",
            post(crate::handler::account::profile::send_verify_phone_post),
        )
        .route(
            "/account/social",
            get(crate::handler::account::social::social_get),
        )
        .route(
            "/account/social/{provider}/bind",
            get(crate::handler::social::initiate::social_bind),
        )
        .route(
            "/account/social/unbind",
            post(crate::handler::account::social::unbind_post),
        )
        .route(
            "/account/change-password",
            get(crate::handler::account::password::change_password_get)
                .post(crate::handler::account::password::change_password_post),
        )
        .route(
            "/account/authorizations",
            get(crate::handler::account::authorizations::authorizations_get),
        )
        .route(
            "/account/authorizations/revoke",
            post(crate::handler::account::authorizations::revoke_post),
        )
        .route(
            "/account/sessions",
            get(crate::handler::account::sessions::sessions_get),
        )
        .route(
            "/account/sessions/delete",
            post(crate::handler::account::sessions::delete_session_post),
        )
        .route(
            "/account/sessions/delete-all",
            post(crate::handler::account::sessions::delete_all_post),
        )
        .route(
            "/account/logout",
            post(crate::handler::account::sessions::logout_post),
        )
}

pub fn login_required_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/users/me",
            get(crate::handler::identity::profile::get_me)
                .put(crate::handler::identity::profile::update_me),
        )
        .route(
            "/api/identity/password/change",
            put(crate::handler::identity::password::change_password),
        )
        .route(
            "/api/identity/unbind/{provider}",
            delete(crate::handler::identity::binding::unbind),
        )
        .route(
            "/api/identity/identities",
            get(crate::handler::identity::binding::list_identities),
        )
        .route(
            "/auth/logout",
            post(crate::handler::identity::login::logout),
        )
        .route(
            "/api/identity/send-verify-email",
            post(crate::handler::sso::verification::send_verify_email_post),
        )
        .route(
            "/api/identity/send-verify-phone",
            post(crate::handler::sso::verification::send_verify_phone_post),
        )
}

pub fn admin_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/users",
            post(crate::handler::identity::registration::create_user),
        )
        .route(
            "/api/users",
            get(crate::handler::identity::profile::list_users),
        )
        .route(
            "/api/users/{id}",
            get(crate::handler::identity::profile::get_user),
        )
        .route(
            "/api/users/{id}",
            put(crate::handler::identity::profile::update_user),
        )
        .route(
            "/api/users/{id}",
            delete(crate::handler::identity::profile::delete_user),
        )
        .route(
            "/api/users/{id}/attributes",
            get(crate::handler::identity::user_attrs::list_attributes),
        )
        .route(
            "/api/users/{id}/attributes",
            put(crate::handler::identity::user_attrs::set_attributes),
        )
        .route(
            "/api/users/{id}/attributes/{key}",
            delete(crate::handler::identity::user_attrs::delete_attribute),
        )
}
